site_name: Museum

nav:
  - Home: index.md 
  
  - Description:
    - Tables: main/tables.md
    - Creation code: main/create.md
    - Data filling: main/fill.md
    - Queries: main/queries.md

  - Mongo:
    - Tables: mongo/mg_tables.md
    - Queries: mongo/mg_queries.md

  - DBProm: db_prom/db_prom.mb

  - PHP: php/php.md

theme:
  name: material
